# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-08 17:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_geoip', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('status', models.CharField(choices=[('active', 'Active'), ('hide', 'Hidden')], db_index=True, default='active', max_length=64, verbose_name='status')),
                ('phone', models.CharField(max_length=20, verbose_name='phone')),
                ('name', models.CharField(max_length=512, verbose_name='name')),
                ('email', models.CharField(blank=True, max_length=128, verbose_name='email')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('range', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_geoip.IpRange', verbose_name='IP range')),
            ],
            options={
                'verbose_name': 'request',
                'verbose_name_plural': 'requests',
                'ordering': ['-pk'],
            },
        ),
    ]
