# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-08 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='city',
            field=models.CharField(blank=True, max_length=255, verbose_name='city'),
        ),
    ]
