# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-09 18:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20170409_2127'),
        ('feedbacks', '0002_request_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='comment',
            field=models.TextField(blank=True, verbose_name='comment'),
        ),
        migrations.AddField(
            model_name='request',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Product', verbose_name='product'),
        ),
    ]
