# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0006_auto_20170415_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='email',
            field=models.EmailField(blank=True, max_length=128, verbose_name='email'),
        ),
    ]
