# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0007_auto_20170422_1750'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, verbose_name='phone')),
                ('email', models.EmailField(max_length=128, verbose_name='email')),
                ('name', models.CharField(blank=True, max_length=512, verbose_name='name')),
                ('address', models.TextField(blank=True, verbose_name='address')),
                ('is_basic', models.BooleanField(default=False, verbose_name='basic')),
            ],
            options={
                'verbose_name': 'seller details',
                'verbose_name_plural': 'seller details',
                'ordering': ['name'],
            },
        ),
    ]
