# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0009_auto_20170422_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=512, verbose_name='name'),
        ),
    ]
