# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-08 15:28
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'gallery',
                'verbose_name_plural': 'galleries',
                'ordering': ['product_id'],
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('picture', models.ImageField(max_length=8192, upload_to='product_images', verbose_name='picture')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(db_index=True, default='active', max_length=64, verbose_name='status')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='name')),
                ('price', models.DecimalField(decimal_places=8, max_digits=28, verbose_name='price')),
                ('discount_rel', models.DecimalField(decimal_places=8, default=0, max_digits=28, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1.0)], verbose_name='relative discount')),
                ('discount_abs', models.DecimalField(decimal_places=8, default=0, max_digits=28, validators=[django.core.validators.MinValueValidator(0)], verbose_name='absolute discount')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Category', verbose_name='category')),
                ('images', models.ManyToManyField(blank=True, through='products.Gallery', to='products.Image')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='gallery',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Image'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product'),
        ),
    ]
