# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-12 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='specification',
            field=models.TextField(blank=True, verbose_name='specification'),
        ),
    ]
